apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  generation: 1
  labels:
    operators.coreos.com/nutanixcsioperator.ntnx-system: ""
  name: nutanixcsioperator
  namespace: ntnx-system
spec:
  channel: stable
  installPlanApproval: Automatic
  name: nutanixcsioperator
  source: certified-operators
  sourceNamespace: openshift-marketplace
